<?xml version="1.0"?>
<package format="3">
  <name>frontier_explorer</name>
  <version>0.0.0</version>
  <description>Frontier-based autonomous exploration node for Stage 1 mapping.</description>
  <maintainer email="evan.chou@live.com">evanc</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
